// <auto-generated />
using System;
using Inlämningsuppgift1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Inlämningsuppgift1.Migrations
{
    [DbContext(typeof(eventsDbContext))]
    [Migration("20210324083821_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Inlämningsuppgift1.Models.Attendee", b =>
                {
                    b.Property<int>("attendeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("attendeeID");

                    b.ToTable("Attendee");
                });

            modelBuilder.Entity("Inlämningsuppgift1.Models.Event", b =>
                {
                    b.Property<int>("eventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("attendeeID")
                        .HasColumnType("int");

                    b.Property<int>("date")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("organizerID")
                        .HasColumnType("int");

                    b.Property<string>("place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("spots_available")
                        .HasColumnType("int");

                    b.HasKey("eventID");

                    b.HasIndex("attendeeID");

                    b.HasIndex("organizerID");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("Inlämningsuppgift1.Models.Organizer", b =>
                {
                    b.Property<int>("organizerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("organizerID");

                    b.ToTable("Organizer");
                });

            modelBuilder.Entity("Inlämningsuppgift1.Models.Event", b =>
                {
                    b.HasOne("Inlämningsuppgift1.Models.Attendee", null)
                        .WithMany("events")
                        .HasForeignKey("attendeeID");

                    b.HasOne("Inlämningsuppgift1.Models.Organizer", "organizer")
                        .WithMany("events")
                        .HasForeignKey("organizerID");

                    b.Navigation("organizer");
                });

            modelBuilder.Entity("Inlämningsuppgift1.Models.Attendee", b =>
                {
                    b.Navigation("events");
                });

            modelBuilder.Entity("Inlämningsuppgift1.Models.Organizer", b =>
                {
                    b.Navigation("events");
                });
#pragma warning restore 612, 618
        }
    }
}
